name: My Portfolio Page
favicon: null
layout_spectrum: 0.21015
typography_spectrum: 0.72746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0c19'
    - '#e6f1f7'
    - '#e1b493'
    - '#507386'
    - '#bb6733'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
